# Agenda

- Fundamentals of Pandas
  - Purpose
  - Features
- Data Structures
- Introduction to Series
  - Creating and accessing Pandas Series using different methods
  - BAsic Information on Series
  - Operations and Transformations on Series
  - Querying a Series
- Introduction to Pandas DataFrane
  - Creating DataFrame using Different Methods
  - Accessing Dataframes
  - Understanding DataFrames Basic
  - Descriptive Statistics
  - Mean, Median Mode And Standard Deviation
  - Correlation Analysis
- Date and Time Delta in pandas
- Date Handling
- TimeDelta in pandas
- Categorical Datahandling
  - Create a Categorical Variable
  - Create dummy Variable
  - Encoding
- Handling Text data in pandas
- Iteration in pandas
- Sorting in pandas
- Plotting through Pandas

- Data Wrangling
  - Data Collection
  - Data Inspection
    - access using iloc an loc
    - Check for missing values
    - Handle missing value
  - Dealing with Duplicates
  - Data Cleaning
  - Data Transformation
  - Data Binning
  - Handling Outliers
  - Merging and Joining Data
  - Data Aggregation
  - Data Reshaping
- Featute Engineering
  - Tranforming Variables
    - Log Transformation
    - Square Root Transformation
    - Boxcox Transformation
  - Feature Scaling
  - Encoding
    - LabelEncoding
    - OneHotEncoding
  - Hashing
  - Grouping

# Fundamentals of Pandas

Pandas is an open-source library built on top of NumPy and is used for data manipulation.
- It introduces data structures like DataFrame and Series that make working with structured data more efficient.

- ![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_04_Working_with_Pandas/1_Introduction_to_Pandas/pandas.png)



__Purpose of Pandas__

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_04_Working_with_Pandas/1_Introduction_to_Pandas/Purpose_of_Pandas.png)


__Features of Pandas__

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Updated_Images/Lesson_4/4_01/Features_of_Pandas.png)

__Data Structures__
The two main libraries of Pandas data structure are:

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_04_Working_with_Pandas/1_Introduction_to_Pandas/Data_Structures.png)

__Introduction to Series__
A Series is a one-dimensional array-like object containing data and labels or index.
It can be created with different data inputs:

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Updated_Images/Lesson_4/4_01/Introduction_to_Series.png) 

 - The Syntax to create Series using pandas is

$\text{pandas.Series(data, index)}$

In [1]:
## Create and access pandas Series using different method

In [2]:
## Install pandas
# !pip install pandas

In [3]:
## let us import libraries
import numpy as np
import pandas as pd

In [4]:
## Creating Series from a list
data  = [1,2,3,4,5]
sr =  pd.Series(data)
print(sr)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
## Creating Series from a list with specified index
data  = [1,2,3,4,5]
index = ['a','b', 'c', 'd', 'e']
sr_with_idx =  pd.Series(data,index =  index)
print(sr_with_idx)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [6]:
## Creating Series from a dictionary 
data_dict  = {'x':1, 'y':2, 'z':5, 'p':3, 'q':9, 'r':4}

sr_from_dict =  pd.Series(data_dict)
print(sr_from_dict)

x    1
y    2
z    5
p    3
q    9
r    4
dtype: int64

In [7]:
## Creating Series from a dictionary  with Specified index
data_dict  = {'x':1, 'y':2, 'z':4, 'p':3, 'q':9, 'r':4}
indx=  ['x', 'y', 'a', 'p', 'q', 'r', 'z', 'b', 'x']
sr_from_dict_idx=  pd.Series(data_dict, index = indx)
print(sr_from_dict_idx)

x    1.0
y    2.0
a    NaN
p    3.0
q    9.0
r    4.0
z    4.0
b    NaN
x    1.0
dtype: float64

In [8]:
print(type(np.nan))

<class 'float'>

In [9]:
## Accessing Values in Series
print(sr_from_dict)

x    1
y    2
z    5
p    3
q    9
r    4
dtype: int64

In [10]:
print(sr_from_dict['z'])
print(sr_from_dict['q'])
print(sr_from_dict[2])
print(sr_from_dict[4])

5
9
5
9

C:\Users\SLP12264\AppData\Local\Temp\ipykernel_8600\690350212.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(sr_from_dict[2])
C:\Users\SLP12264\AppData\Local\Temp\ipykernel_8600\690350212.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(sr_from_dict[4])

Whenever accesing values in pandas use loc and iloc to access the data
- use loc when trying to access the data from user defined indices
- use iloc when trying to access the data from default integer index

__loc and iloc can also be used for slicing. To be discussed with dataframes__

In [11]:
print(sr_from_dict.loc['z'])
print(sr_from_dict.loc['q'])
print(sr_from_dict.iloc[2])
print(sr_from_dict.iloc[4])

5
9
5
9

In [12]:
list1 =  [1,2,3,4,5,6,7,8,9,0]

In [13]:
print(list1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]

In [14]:
print(list1[3], list1[4], list1[5], list1[6], list1[7])

4 5 6 7 8

In [15]:
print(list1[::1])

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]

In [16]:
print(list1[::-1])

[0, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [17]:
### Basic Information in Pandas Series


print(sr_from_dict.ndim)
print(sr_from_dict.shape)
print(sr_from_dict.size)
print(sr_from_dict.dtype)
print(sr_from_dict.index)
print(sr_from_dict.values)

1
(6,)
6
int64
Index(['x', 'y', 'z', 'p', 'q', 'r'], dtype='object')
[1 2 5 3 9 4]

In [18]:
print(sr_from_dict.head(3))  # Display first 5 rows or as many mentioned in paranthesis
print(sr_from_dict.tail(4))  # Displa last 5 rows or as many mentioned in paranthesis
print(sr_from_dict.describe()) # Display Statistical Summary of the data

print(sr_from_dict.info()) # Display General Summary of the data

print(sr_from_dict.unique()) # Display list of unique values in the series

print(sr_from_dict.nunique()) # Display number of unique values in the series

x    1
y    2
z    5
dtype: int64
z    5
p    3
q    9
r    4
dtype: int64
count    6.000000
mean     4.000000
std      2.828427
min      1.000000
25%      2.250000
50%      3.500000
75%      4.750000
max      9.000000
dtype: float64
<class 'pandas.core.series.Series'>
Index: 6 entries, x to r
Series name: None
Non-Null Count  Dtype
--------------  -----
6 non-null      int64
dtypes: int64(1)
memory usage: 268.0+ bytes
None
[1 2 5 3 9 4]
6

# __Date: 09-08-2025__

## Operations and Transformations in Pandas Series

In [19]:
print(sr)
print(sr_with_idx)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64

In [20]:
## element wise addition

result =  sr + sr_with_idx
print(result)

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
a   NaN
b   NaN
c   NaN
d   NaN
e   NaN
dtype: float64

In [21]:
srnew =  pd.Series([2,3,6,7,8])
print(srnew)

0    2
1    3
2    6
3    7
4    8
dtype: int64

In [22]:
print(sr + srnew)

0     3
1     5
2     9
3    11
4    13
dtype: int64

In [23]:
# Apply a function to each element of the series

sq_srnew =  srnew.apply(lambda x: x**2)
print(sq_srnew)

0     4
1     9
2    36
3    49
4    64
dtype: int64

In [24]:
## Map values using a dictionary

sr_mapped = sr.map({1:'One', 2:'Two', 5:'Five'})
print(sr_mapped)

0     One
1     Two
2     NaN
3     NaN
4    Five
dtype: object

In [25]:
sr_replaced = sr.replace({1:'One', 2:'Two', 5:'Five'})
print(sr_replaced)

0     One
1     Two
2       3
3       4
4    Five
dtype: object

In [26]:
## Sorting the series

sr1 =  pd.Series(np.random.randint(1,100, 10))
print(sr1)

0    79
1    49
2    62
3    42
4    14
5    12
6    70
7    49
8     1
9    94
dtype: int32

In [27]:
## Sort the Series based on values
sorted_sr1_asc =  sr1.sort_values(ascending = True)
sorted_sr1_desc =  sr1.sort_values(ascending = False)

In [28]:
sorted_sr1_desc

9    94
0    79
6    70
2    62
1    49
7    49
3    42
4    14
5    12
8     1
dtype: int32

In [29]:
# reset the index to default index
sr1_desc_def_idx =  sorted_sr1_desc.reset_index(drop = True)
sr1_desc_def_idx

0    94
1    79
2    70
3    62
4    49
5    49
6    42
7    14
8    12
9     1
dtype: int32

In [30]:
# Sort Series on Index

sorted_sr1_desc.sort_index(ascending = False)

9    94
8     1
7    49
6    70
5    12
4    14
3    42
2    62
1    49
0    79
dtype: int32

In [31]:
print(sr_from_dict_idx)

x    1.0
y    2.0
a    NaN
p    3.0
q    9.0
r    4.0
z    4.0
b    NaN
x    1.0
dtype: float64

In [32]:
# notna() -  Check if value a is present at an index and give true if there is value else false
print(sr_from_dict_idx.notna())

x     True
y     True
a    False
p     True
q     True
r     True
z     True
b    False
x     True
dtype: bool

In [33]:
# Check for a missing Value
## isna() - Check if value is not present at an index and give true if there is no value else false
## isnull() is a replica of isna()

missing_values  = sr_from_dict_idx.isna()
print(missing_values)

x    False
y    False
a     True
p    False
q    False
r    False
z    False
b     True
x    False
dtype: bool

In [34]:
missing_values  = sr_from_dict_idx.isnull()
print(missing_values)

x    False
y    False
a     True
p    False
q    False
r    False
z    False
b     True
x    False
dtype: bool

In [35]:
# We can use the response of isnull() to find the count of missing value by chaining sum()

print(f'Number of Missing Values {sr_from_dict_idx.isnull().sum()}')

Number of Missing Values 2

Generally Majority of ML models has requirement that there should not be any missing data the training data given to them. Hence Filling up the missing values is an important step while preprocessing the data for modelling. In order to treat missing Values we have multiple choices
- remove the missing value
    - Removing data from the original is not recommended as it may cause loss on information. However if the amount of missing data is beyond a threshold(usually 30%) we prefer dropping data.(to be done with prior consent from the stakeholders)
- Fill the missing value with an appropriate(synthetic)value
  - There can multiple thoughts to replace the missing value in a series keeping in consideration that the meaning of data before and after the treatment values does not vary significantly
    - Replace it with a constant
    - Replace it with measure of central tendency
    - Replace with a string

In [36]:
sr_from_dict_idx.describe()

count    7.000000
mean     3.428571
std      2.760262
min      1.000000
25%      1.500000
50%      3.000000
75%      4.000000
max      9.000000
dtype: float64

In [37]:
# Use fillna() - replace the missing values with data in paranthesis
sr_from_dict_idx.fillna(sr_from_dict_idx.median())

x    1.0
y    2.0
a    3.0
p    3.0
q    9.0
r    4.0
z    4.0
b    3.0
x    1.0
dtype: float64

# Querying a Series
selecting an filtering data based oin specific condition

In [38]:
sr =  pd.Series({'a':10, 'b':20, 'c':30, 'd':40, 'e':50, 'f':60})
print(sr)

a    10
b    20
c    30
d    40
e    50
f    60
dtype: int64

In [39]:
## select elements greater than 30
print(sr[sr>30])

d    40
e    50
f    60
dtype: int64

In [40]:
## select elements equal to 20
print(sr[sr==20])

b    20
dtype: int64

In [41]:
## select elements not equal to 40

print(sr[sr!=40])

a    10
b    20
c    30
e    50
f    60
dtype: int64

In [42]:
## select elements greater than 20 and less than 50
print(sr[(sr>20) & (sr<50)])

c    30
d    40
dtype: int64

In [43]:
## select elements based on a list [20, 40, 50] 

print(sr[sr.isin([20, 40, 50])])

b    20
d    40
e    50
dtype: int64

In [44]:
## select elements based on string methods

str_series =  pd.Series(['apple', 'bananas', 'cherry', 'date', 'elderberry'])

In [45]:
## select elements based on string methods

str_series =  pd.Series(['apple', 'bananas', 'cherry', 'date', 'elderberry'])

In [46]:
print(str_series[str_series.str.contains('a')])

0      apple
1    bananas
3       date
dtype: object

In [47]:
# Choosing random sample for better understanding of the data
### sample() - display 1 or as many mentioned in paranthesis chosen randomly from the series
print(sr.sample(3))

a    10
e    50
d    40
dtype: int64

# __Pandas DataFrame__

A Pandas DataFrame is a two-dimensional, tabular data structure with labeled axes (rows and columns).
It is a primary data structure in the Pandas library, providing a versatile and efficient way to handle and manipulate data in Python.

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_04_Working_with_Pandas/2_Introduction_to_DataFrame/Introduction_to_Pandas_DataFrame.png)

### __Key Features:__
- __Tabular structure:__ The DataFrame is organized as a table with rows and columns, similar to a spreadsheet or SQL table.
- __Labeled axes:__ Both rows and columns are labeled, allowing for easy indexing and referencing of data.
- __Heterogeneous data types:__ Each column in a DataFrame can contain different types of data, such as integers, floats, strings, or even complex objects.
- __Versatility:__ DataFrames can store and handle a wide range of data formats, including CSV, Excel, SQL databases, and more.
- __Data alignment:__ Operations on DataFrames are designed to handle missing values gracefully, aligning data based on labels.

__Creating a DataFrame Using Different Methods__

Creating a Pandas DataFrame is a fundamental step in data analysis and manipulation.
- Diverse methods are available within Pandas to generate a DataFrame, addressing various data sources and structures.
- Data, whether in Python dictionaries, lists, NumPy arrays, or external files such as CSV and Excel, can be seamlessly transformed into a structured tabular format by Pandas.

In [48]:
# Creating a dataframe from a dictionary
import pandas as pd

data_dict = {'Name': ['Alice', 'Bob', 'Charlie'], 
            'Age': [25, 30, 22], 
            'Salary':[50000, 60000, 45000]}

df_dict =  pd.DataFrame(data_dict)

In [49]:
print(df_dict)

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   22   45000

In [50]:
df_dict

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   22   45000

In [51]:
# Creating DataFrame using list of list

data_list =  [['Alice',	25,50000], ['Bob',30,60000], ['Charlie',22,45000]]

df_list =  pd.DataFrame(data_list, columns = ['NAME', 'AGE', 'SALARY'])

df_list

      NAME  AGE  SALARY
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   22   45000

In [52]:
# Creating DataFrame using array

import numpy as np

data_array =  np.array([['Alice',	25,50000], ['Bob',30,60000], ['Charlie',22,45000]])

df_ary =  pd.DataFrame(data_array, columns = ['NAME', 'AGE', 'SALARY'])

df_ary

      NAME AGE SALARY
0    Alice  25  50000
1      Bob  30  60000
2  Charlie  22  45000

In [53]:
# Creating dataframe with user index

data_array =  np.array([['Alice',	25,50000], ['Bob',30,60000], ['Charlie',22,45000]])

df_ary_with_row_idx =  pd.DataFrame(data_array, columns = ['NAME', 'AGE', 'SALARY'], 
                       index=['emp1', 'emp2', 'emp3'] )

df_ary_with_row_idx

         NAME AGE SALARY
emp1    Alice  25  50000
emp2      Bob  30  60000
emp3  Charlie  22  45000

#### Creating DataFrame from an external file

to create dataframes out of external file like csv, xlsx, html, json, sql query etc pandas offers various function, the syntax in general can be represented as

dfname = pd.read_FileTypeBasedKeyword(Absolute path to the file)

In [54]:
df_csv=  pd.read_csv(r'C:\Users\SLP12264\Downloads\Houseprices.csv')
df_excel=  pd.read_excel('iris.xlsx')

In [55]:
df_csv

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,3.130000e+05,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2.384000e+06,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,3.420000e+05,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,4.200000e+05,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,5.500000e+05,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,2014-07-09 00:00:00,3.081667e+05,3.0,1.75,1510,6360,1.0,0,0,4,1510,0,1954,1979,501 N 143rd St,Seattle,WA 98133,USA
4596,2014-07-09 00:00:00,5.343333e+05,3.0,2.50,1460,7573,2.0,0,0,3,1460,0,1983,2009,14855 SE 10th Pl,Bellevue,WA 98007,USA
4597,2014-07-09 00:00:00,4.169042e+05,3.0,2.50,3010,7014,2.0,0,0,3,3010,0,2009,0,759 Ilwaco Pl NE,Renton,WA 98059,USA
4598,2014-07-10 00:00:00,2.034000e+05,4.0,2.00,2090,6630,1.0,0,0,3,1070,1020,1974,0,5148 S Creston St,Seattle,WA 98178,USA
4599,2014-07-10 00:00:00,2.206000e+05,3.0,2.50,1490,8102,2.0,0,0,4,1490,0,1990,0,18717 SE 258th St,Covington,WA 98042,USA

In [56]:
df_excel

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

## Accessing DataFrames


Accessing a Pandas DataFrame involves employing various methods for selecting and retrieving data, whether it be specific columns, rows, or individual cells.
- Utilizing square brackets, iloc and loc indexers, and conditions, analysts can navigate and extract the necessary information from the DataFrame for further analysis and manipulation.
- The flexibility of Pandas allows for both label-based and position-based indexing, offering a versatile toolkit for accessing and working with data efficiently.

In [57]:
## Accessing a single column

df_csv['price']

0       3.130000e+05
1       2.384000e+06
2       3.420000e+05
3       4.200000e+05
4       5.500000e+05
            ...
4595    3.081667e+05
4596    5.343333e+05
4597    4.169042e+05
4598    2.034000e+05
4599    2.206000e+05
Name: price, Length: 4600, dtype: float64

In [58]:
# df_csv.price

In [59]:
## Accessing a multiple column

df_csv[['price', 'bedrooms']]

             price  bedrooms
0     3.130000e+05       3.0
1     2.384000e+06       5.0
2     3.420000e+05       3.0
3     4.200000e+05       3.0
4     5.500000e+05       4.0
...            ...       ...
4595  3.081667e+05       3.0
4596  5.343333e+05       3.0
4597  4.169042e+05       3.0
4598  2.034000e+05       4.0
4599  2.206000e+05       3.0

[4600 rows x 2 columns]

In [60]:
## Accessing Specific row by index

df_csv.iloc[0]

date              2014-05-02 00:00:00
price                        313000.0
bedrooms                          3.0
bathrooms                         1.5
sqft_living                      1340
sqft_lot                         7912
floors                            1.5
waterfront                          0
view                                0
condition                           3
sqft_above                       1340
sqft_basement                       0
yr_built                         1955
yr_renovated                     2005
street           18810 Densmore Ave N
city                        Shoreline
statezip                     WA 98133
country                           USA
Name: 0, dtype: object

In [61]:
## Accessing  row based on condition

df_csv[df_csv['price']<50000]

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
4351,2014-05-06 00:00:00,7800.0,2.0,1.00,780,16344,1.0,0,0,1,780,0,1942,0,4229 S 144th St,Tukwila,WA 98168,USA
4354,2014-05-05 00:00:00,0.0,3.0,1.75,1490,10125,1.0,0,0,4,1490,0,1962,0,3911 S 328th St,Federal Way,WA 98001,USA
4356,2014-05-05 00:00:00,0.0,4.0,2.75,2600,5390,1.0,0,0,4,1300,1300,1960,2001,2120 31st Ave W,Seattle,WA 98199,USA
4357,2014-05-05 00:00:00,0.0,6.0,2.75,3200,9200,1.0,0,2,4,1600,1600,1953,1983,12271 Marine View Dr SW,Burien,WA 98146,USA
4358,2014-05-06 00:00:00,0.0,5.0,3.50,3480,36615,2.0,0,0,4,2490,990,1983,0,21809 SE 38th Pl,Issaquah,WA 98075,USA
4361,2014-05-07 00:00:00,0.0,5.0,1.50,1500,7112,1.0,0,0,5,760,740,1920,0,14901-14999 12th Ave SW,Burien,WA 98166,USA
4362,2014-05-07 00:00:00,0.0,4.0,4.00,3680,18804,2.0,0,0,3,3680,0,1990,2009,1223-1237 244th Ave NE,Sammamish,WA 98074,USA
4374,2014-05-09 00:00:00,0.0,2.0,2.50,2200,188200,1.0,0,3,3,2200,0,2007,0,39612 254th Ave SE,Enumclaw,WA 98022,USA
4376,2014-05-09 00:00:00,0.0,4.0,2.25,2170,10500,1.0,0,2,4,1270,900,1960,2001,216 SW 183rd St,Normandy Park,WA 98166,USA
4382,2014-05-12 00:00:00,0.0,5.0,4.50,4630,6324,2.0,0,0,3,3210,1420,2006,0,6925 Oakmont Ave SE,Snoqualmie,WA 98065,USA
4383,2014-05-13 00:00:00,0.0,5.0,4.00,4430,9000,2.0,0,0,3,4430,0,2013,1923,9235 NE 5th St,Bellevue,WA 98004,USA
4385,2014-05-13 00:00:00,0.0,4.0,4.50,5030,11023,2.0,0,2,3,3250,1780,2008,0,4140 Boulevard Pl,Mercer Island,WA 98040,USA
4386,2014-05-13 00:00:00,0.0,4.0,1.50,2180,22870,1.0,0,0,4,1280,900,1954,1975,31603 E Lake Morton Dr SE,Kent,WA 98042,USA
4389,2014-05-15 00:00:00,0.0,4.0,3.50,4210,10308,2.0,0,0,3,4210,0,2006,0,2234 167th Ave SE,Bellevue,WA 98008,USA
4394,2014-05-16 00:00:00,0.0,5.0,3.25,3690,12353,2.0,0,0,5,3690,0,1977,0,19055 35th Ave NE,Lake Forest Park,WA 98155,USA
4405,2014-05-20 00:00:00,0.0,4.0,3.75,3300,4545,1.5,0,4,3,2600,700,1926,1999,3665 50th Ave NE,Seattle,WA 98105,USA
4408,2014-05-21 00:00:00,0.0,5.0,2.25,2880,11965,2.0,0,0,4,2880,0,1990,0,25437 163rd Pl SE,Covington,WA 98042,USA
4411,2014-05-22 00:00:00,0.0,5.0,2.25,2000,7900,1.0,0,0,4,1300,700,1986,0,3202 S 194th St,SeaTac,WA 98188,USA
4412,2014-05-22 00:00:00,0.0,3.0,3.00,1860,7440,1.0,0,0,5,1040,820,1954,0,10744 62nd Ave S,Seattle,WA 98178,USA
4413,2014-05-22 00:00:00,0.0,4.0,3.00,1990,6180,2.0,0,0,3,1990,0,1990,2009,32706 20th Ave SW,Federal Way,WA 98023,USA
4420,2014-05-27 00:00:00,0.0,4.0,1.00,1360,13372,1.0,0,0,3,1360,0,1955,2005,18423 61st Pl NE,Kenmore,WA 98028,USA
4442,2014-06-02 00:00:00,0.0,1.0,1.00,720,6000,1.0,0,0,3,720,0,1940,1996,1236 S Cloverdale St,Seattle,WA 98108,USA
4448,2014-06-03 00:00:00,0.0,5.0,2.75,2740,5616,1.5,0,0,5,1670,1070,1925,0,1013 NE 80th St,Seattle,WA 98115,USA
4453,2014-06-03 00:00:00,0.0,3.0,1.00,1300,6710,1.0,0,0,4,1300,0,1952,0,2760 72nd Ave SE,Mercer Island,WA 98040,USA
4454,2014-06-03 00:00:00,0.0,5.0,2.50,2090,4698,2.0,0,0,3,2090,0,1998,2006,27622 237th Pl SE,Maple Valley,WA 98038,USA
4472,2014-06-09 00:00:00,0.0,4.0,3.75,4060,19290,2.0,0,0,3,4060,0,2002,0,21418 SE 5th Pl,Sammamish,WA 98074,USA
4478,2014-06-11 00:00:00,0.0,5.0,2.75,2910,53898,1.0,0,0,5,1510,1400,1979,0,13505 208th Ave NE,Woodinville,WA 98077,USA
4479,2014-06-11 00:00:00,0.0,5.0,2.00,1910,7200,1.0,0,0,4,1110,800,1951,1999,11620-11698 57th Ave S,Seattle,WA 98178,USA
4480,2014-06-11 00:00:00,0.0,3.0,2.50,2880,13500,1.0,0,4,5,1520,1360,1950,0,9243 NE 20th St,Clyde Hill,WA 98004,USA
4481,2014-06-11 00:00:00,0.0,5.0,2.75,3240,6863,2.0,0,0,3,3240,0,2013,1923,1301-1303 Monterey Ave NE,Renton,WA 98056,USA
4487,2014-06-12 00:00:00,0.0,4.0,1.00,2080,3500,1.5,0,0,5,1260,820,1926,0,6506 40th Ave SW,Seattle,WA 98136,USA
4499,2014-06-17 00:00:00,0.0,5.0,3.75,3870,8225,2.0,0,0,3,3870,0,1998,2006,101-127 247th Ave SE,Sammamish,WA 98074,USA
4507,2014-06-18 00:00:00,0.0,4.0,1.50,2310,68824,2.0,0,0,4,2310,0,1968,0,29656 232nd Ave SE,Black Diamond,WA 98010,USA
4509,2014-06-18 00:00:00,0.0,6.0,3.00,3020,13783,2.0,0,0,3,3020,0,1952,2002,4115 85th Ave SE,Mercer Island,WA 98040,USA
4520,2014-06-20 00:00:00,0.0,4.0,2.50,1960,11600,1.0,0,0,5,980,980,1931,0,506 21st St SE,Auburn,WA 98002,USA
4521,2014-06-20 00:00:00,0.0,4.0,1.00,1810,7500,1.0,0,0,2,1410,400,1959,0,12231 Occidental Ave S,Seattle,WA 98168,USA
4522,2014-06-22 00:00:00,0.0,2.0,2.25,1490,6770,1.5,0,0,3,1490,0,1926,2003,4921 28th Ave S,Seattle,WA 98108,USA
4523,2014-06-23 00:00:00,0.0,3.0,4.50,5230,17826,2.0,1,4,3,3740,1490,2005,0,7455 W Mercer Way,Mercer Island,WA 98040,USA
4528,2014-06-24 00:00:00,0.0,4.0,5.00,4550,18641,1.0,1,4,3,2600,1950,2002,0,425 E Lake Sammamish Pkwy SE,Sammamish,WA 98074,USA
4534,2014-06-24 00:00:00,0.0,3.0,2.75,1310,7300,1.0,0,0,3,1310,0,1957,2000,16232 SE 10th St,Bellevue,WA 98008,USA
4542,2014-06-25 00:00:00,0.0,5.0,3.50,2640,6895,2.0,0,0,3,2640,0,2001,0,34529 SE Jay Ct,Snoqualmie,WA 98065,USA
4552,2014-06-26 00:00:00,0.0,4.0,2.00,2100,4857,2.0,0,0,3,2100,0,1965,1984,4500 NE 171st St,Lake Forest Park,WA 98155,USA
4554,2014-06-27 00:00:00,0.0,2.0,1.00,810,8424,1.0,0,0,4,810,0,1959,0,30401-30499 8th Ave SW,Federal Way,WA 98023,USA
4555,2014-06-27 00:00:00,0.0,2.0,1.50,1520,8040,1.0,0,0,5,1520,0,1951,0,11533 22nd Ave NE,Seattle,WA 98125,USA
4558,2014-06-28 00:00:00,0.0,4.0,4.25,3500,8750,1.0,0,4,5,2140,1360,1951,0,12725 8th Ave NW,Seattle,WA 98177,USA
4563,2014-07-01 00:00:00,0.0,2.0,2.25,2130,4920,1.5,0,4,4,1530,600,1941,1998,3428 60th Ave SW,Seattle,WA 98116,USA
4567,2014-07-02 00:00:00,0.0,4.0,2.50,4080,18362,2.0,0,2,4,4080,0,1983,0,2710 95th Ave NE,Clyde Hill,WA 98004,USA
4574,2014-07-02 00:00:00,0.0,3.0,1.00,1520,9030,1.0,0,0,3,1520,0,1956,2001,2533 155th Pl SE,Bellevue,WA 98007,USA
4575,2014-07-02 00:00:00,0.0,5.0,6.25,8020,21738,2.0,0,0,3,8020,0,2001,0,2 Crescent Key,Bellevue,WA 98006,USA
4588,2014-07-08 00:00:00,0.0,4.0,2.25,2890,18226,3.0,1,4,3,2890,0,1984,0,3227-3399 Mountain View Ave N,Renton,WA 98056,USA

In [62]:
## Accessing  row based on multiple condition

df_csv[(df_csv['price']<50000 ) & (df_csv['yr_built']> 2010)]

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
4383,2014-05-13 00:00:00,0.0,5.0,4.00,4430,9000,2.0,0,0,3,4430,0,2013,1923,9235 NE 5th St,Bellevue,WA 98004,USA
4481,2014-06-11 00:00:00,0.0,5.0,2.75,3240,6863,2.0,0,0,3,3240,0,2013,1923,1301-1303 Monterey Ave NE,Renton,WA 98056,USA

In [63]:
# Select random row sample

df_csv.sample(3)

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
4205,2014-07-09 00:00:00,410000.0,3.0,1.75,1660,6250,1.0,0,0,3,830,830,1980,0,1919 42nd Ave SW,Seattle,WA 98116,USA
2913,2014-06-19 00:00:00,330000.0,3.0,2.50,2238,7209,2.0,0,0,3,2238,0,2011,0,1326 SW 340th St,Federal Way,WA 98023,USA
2828,2014-06-19 00:00:00,450000.0,3.0,1.75,1610,11200,1.0,0,0,3,1610,0,1955,2005,12234 NE 65th St,Kirkland,WA 98033,USA

In [64]:
##Access specific cell data

### using row index and column label
print(df_csv.loc[2764, 'sqft_living'])

### using row index and column num index
print(df_csv.iloc[2764, 4])

2660
2660

In [65]:
## Conditional Access

df_csv[df_csv['price']<50000]['price']

4351    7800.0
4354       0.0
4356       0.0
4357       0.0
4358       0.0
4361       0.0
4362       0.0
4374       0.0
4376       0.0
4382       0.0
4383       0.0
4385       0.0
4386       0.0
4389       0.0
4394       0.0
4405       0.0
4408       0.0
4411       0.0
4412       0.0
4413       0.0
4420       0.0
4442       0.0
4448       0.0
4453       0.0
4454       0.0
4472       0.0
4478       0.0
4479       0.0
4480       0.0
4481       0.0
4487       0.0
4499       0.0
4507       0.0
4509       0.0
4520       0.0
4521       0.0
4522       0.0
4523       0.0
4528       0.0
4534       0.0
4542       0.0
4552       0.0
4554       0.0
4555       0.0
4558       0.0
4563       0.0
4567       0.0
4574       0.0
4575       0.0
4588       0.0
Name: price, dtype: float64

# __Understanding DataFrame Basics__
- The head() and tail() methods enable users to efficiently preview the initial and final rows of a DataFrame, offering a quick snapshot of its structure and content.
- These functions are invaluable for a preliminary assessment of column names, data types, and potential issues. Additionally, the info() method provides a comprehensive summary, detailing data types, non-null counts, and memory usage, aiding in the identification of missing or inconsistent data.
- The shape attribute, on the other hand, succinctly communicates the dimensions of the DataFrame, encapsulating the number of rows and columns.
- The syntax for some functions is provided below:

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_04_Working_with_Pandas/2_Introduction_to_DataFrame/Understanding_DataFrame_Basics.png)

#  __Date: 10-08-2025__

In [66]:
# Working with walmart Sales data for understanding basic of pandas dataframe

In [67]:
# import libraries 
import numpy as np
import pandas as pd

In [68]:
# Read the file

df =  pd.read_csv('walmart_store_sales.csv')

In [69]:
# View Top 5 rows
df.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,19-02-2010,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,05-03-2010,1554806.68,0,46.50,2.625,211.350143,8.106

In [70]:
# View last 5 rows
df.tail()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
6430,45,28-09-2012,713173.95,0,64.88,3.997,192.013558,8.684
6431,45,05-10-2012,733455.07,0,64.89,3.985,192.170412,8.667
6432,45,12-10-2012,734464.36,0,54.47,4.000,192.327265,8.667
6433,45,19-10-2012,718125.53,0,56.47,3.969,192.330854,8.667
6434,45,26-10-2012,760281.43,0,58.85,3.882,192.308899,8.667

In [71]:
## View the general summary
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6435 entries, 0 to 6434
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Store         6435 non-null   int64
 1   Date          6435 non-null   object
 2   Weekly_Sales  6435 non-null   float64
 3   Holiday_Flag  6435 non-null   int64
 4   Temperature   6435 non-null   float64
 5   Fuel_Price    6435 non-null   float64
 6   CPI           6435 non-null   float64
 7   Unemployment  6435 non-null   float64
dtypes: float64(5), int64(2), object(1)
memory usage: 402.3+ KB

Observations:
- There are missing values in any columns
- The Date column is of object type and requires conversion to datetime format
- Holiday_Flag is a categorical variable  represented in nominal form 0 - non holiday, 1- holiday

In [72]:
# Let observe the shape of the dataframe

print(df.shape)

(6435, 8)

In [73]:
## Statistical Summary - Numeric data only

df.describe()

,Store,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
count,6435.000000,6.435000e+03,6435.000000,6435.000000,6435.000000,6435.000000,6435.000000
mean,23.000000,1.046965e+06,0.069930,60.663782,3.358607,171.578394,7.999151
std,12.988182,5.643666e+05,0.255049,18.444933,0.459020,39.356712,1.875885
min,1.000000,2.099862e+05,0.000000,-2.060000,2.472000,126.064000,3.879000
25%,12.000000,5.533501e+05,0.000000,47.460000,2.933000,131.735000,6.891000
50%,23.000000,9.607460e+05,0.000000,62.670000,3.445000,182.616521,7.874000
75%,34.000000,1.420159e+06,0.000000,74.940000,3.735000,212.743293,8.622000
max,45.000000,3.818686e+06,1.000000,100.140000,4.468000,227.232807,14.313000

__Observations__
- Data appears to near normal distribution however it in not in standard form(mean and std across columns is varying) , hence requires standardization
- Few columns like Weekly_Sales and Unemployement appears to have outliers data and need to verify through boxplot and take corrective measure using winsorization method.

In [74]:
## Statistical Summary - Non Numeric data only

df.describe(exclude =  'number')

              Date
count         6435
unique         143
top     05-02-2010
freq            45

In [75]:
# Display the list of colums

colnames =  df.columns
colnames

Index(['Store', 'Date', 'Weekly_Sales', 'Holiday_Flag', 'Temperature',
       'Fuel_Price', 'CPI', 'Unemployment'],
      dtype='object')

### Convert the datatype from one type to another for a column (except dates)
The Conversion can be done from any dtype to any dtype given it has valid data to convert

In [76]:
# change the dtype of Holiday_Flag to category

df['Holiday_Flag']  = df['Holiday_Flag'].astype('category')

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6435 entries, 0 to 6434
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Store         6435 non-null   int64
 1   Date          6435 non-null   object
 2   Weekly_Sales  6435 non-null   float64
 3   Holiday_Flag  6435 non-null   category
 4   Temperature   6435 non-null   float64
 5   Fuel_Price    6435 non-null   float64
 6   CPI           6435 non-null   float64
 7   Unemployment  6435 non-null   float64
dtypes: category(1), float64(5), int64(1), object(1)
memory usage: 358.4+ KB

In [78]:
# Seggregate dataframe based on the column data types

num_data =  df.select_dtypes(include ='number')
cat_data =  df.select_dtypes(exclude ='number')

print(num_data.columns)

print(cat_data.columns)

Index(['Store', 'Weekly_Sales', 'Temperature', 'Fuel_Price', 'CPI',
       'Unemployment'],
      dtype='object')
Index(['Date', 'Holiday_Flag'], dtype='object')

In [82]:
# Statistical Operations in pandas

## Mean, Median, Standard Deviation, Variance, Covariance, Correlation

print(f'Mean - \n {num_data.mean()}')
print('-'*50)
print(f'Median - \n {num_data.median()}')
print('-'*50)
print(f'Standard Deviation - \n {num_data.std()}')
print('-'*50)
print(f'Variance - \n {num_data.var()}')

Mean -
 Store           2.300000e+01
Weekly_Sales    1.046965e+06
Temperature     6.066378e+01
Fuel_Price      3.358607e+00
CPI             1.715784e+02
Unemployment    7.999151e+00
dtype: float64
--------------------------------------------------
Median -
 Store               23.000000
Weekly_Sales    960746.040000
Temperature         62.670000
Fuel_Price           3.445000
CPI                182.616521
Unemployment         7.874000
dtype: float64
--------------------------------------------------
Standard Deviation -
 Store               12.988182
Weekly_Sales    564366.622054
Temperature         18.444933
Fuel_Price           0.459020
CPI                 39.356712
Unemployment         1.875885
dtype: float64
--------------------------------------------------
Variance -
 Store           1.686929e+02
Weekly_Sales    3.185097e+11
Temperature     3.402155e+02
Fuel_Price      2.106991e-01
CPI             1.548951e+03
Unemployment    3.518944e+00
dtype: float64

In [83]:

print(f'Co Variance Matrix')
num_data.cov()

Co Variance Matrix

,Store,Weekly_Sales,Temperature,Fuel_Price,CPI,Unemployment
Store,1.686929e+02,-2.458016e+06,-5.428348,0.357847,-1.070864e+02,5.446191
Weekly_Sales,-2.458016e+06,3.185097e+11,-664243.378859,2451.644964,-1.613322e+06,-112407.220105
Temperature,-5.428348e+00,-6.642434e+05,340.215549,1.227501,1.284084e+02,3.500119
Fuel_Price,3.578468e-01,2.451645e+03,1.227501,0.210699,-3.082730e+00,-0.029865
CPI,-1.070864e+02,-1.613322e+06,128.408410,-3.082730,1.548951e+03,-22.297736
Unemployment,5.446191e+00,-1.124072e+05,3.500119,-0.029865,-2.229774e+01,3.518944

## Correlation Analysis
The corr() generates correaltion matrix for number 2d data, indicating how variables(columns) relate to each other
- The correlation value will be between -1 to +1 . Values closer to extremes(-1, +1) indicate strong relation while values near 0 indicate weak relation

In [84]:
# C
print(f'Correlation Matrix')
num_data.corr()

Correlation Matrix

,Store,Weekly_Sales,Temperature,Fuel_Price,CPI,Unemployment
Store,1.000000,-0.335332,-0.022659,0.060023,-0.209492,0.223531
Weekly_Sales,-0.335332,1.000000,-0.063810,0.009464,-0.072634,-0.106176
Temperature,-0.022659,-0.063810,1.000000,0.144982,0.176888,0.101158
Fuel_Price,0.060023,0.009464,0.144982,1.000000,-0.170642,-0.034684
CPI,-0.209492,-0.072634,0.176888,-0.170642,1.000000,-0.302020
Unemployment,0.223531,-0.106176,0.101158,-0.034684,-0.302020,1.000000

## Value_counts()

it tells the frequency of all unique values in a series. i.e. frequency distribution of a series values

In [86]:
print(df['Holiday_Flag'].value_counts())

Holiday_Flag
0    5985
1     450
Name: count, dtype: int64

In [90]:
print(df['Holiday_Flag'].value_counts())

Holiday_Flag
0    5985
1     450
Name: count, dtype: int64

## Date and TimeDeltas

In Pandas, the datetime module gives functionalities to handles dates and time data, whereas Timedelta class allows for convinient manipulation of time intervals

In [93]:
print(df['Date'].dtype)

object

In [96]:
print(type(df['Date'][0]))

<class 'str'>

In [98]:
df['Date'][0]

'05-02-2010'

 A Date data should be considered as date and not as string to utilize the values for any processing. There for if the daatframe contains Date values in any format, we must convert the datatype of that column to datetime

In [105]:
# convert the column to datetime format

df['Date'] = pd.to_datetime(df['Date'], format = "%d-%m-%Y" )

In [106]:
print(df['Date'].dtype)

datetime64[ns]

In [107]:
print(type(df['Date'][0]))

<class 'pandas._libs.tslibs.timestamps.Timestamp'>

In [108]:
print(df['Date'][0])

2010-02-05 00:00:00

In [112]:
print(df['Date'][0].day)
print(df['Date'][0].month)
print(df['Date'][0].year)
print(df['Date'][0].hour)
print(df['Date'][0].minute)
print(df['Date'][0].second)
print(df['Date'][0].weekday())

5
2
2010
0
0
0
4

In [121]:
#epoch time
start  = pd.Timestamp('2010-02-05 00:00:00')

df['DaysSinceStart'] = df['Date'] - start

In [122]:
df.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,DaysSinceEpoch,DaysSinceStart
0,1,2010-02-05,1643690.90,0,42.31,2.572,211.096358,8.106,0 days,0 days
1,1,2010-02-12,1641957.44,1,38.51,2.548,211.242170,8.106,7 days,7 days
2,1,2010-02-19,1611968.17,0,39.93,2.514,211.289143,8.106,14 days,14 days
3,1,2010-02-26,1409727.59,0,46.63,2.561,211.319643,8.106,21 days,21 days
4,1,2010-03-05,1554806.68,0,46.50,2.625,211.350143,8.106,28 days,28 days

In [129]:
## time delta

delta = pd.Timedelta('3 Days 2 Hours 34 Minutes 4 Seconds')
delta

Timedelta('3 days 02:34:04')

In [127]:
start  + delta

Timestamp('2010-02-08 02:34:04')

In [128]:
start  - delta

Timestamp('2010-02-01 21:25:56')

## Resampling Time Series Data

Time series data often comes with irregular time intervals. Resampling is the process of changing the frequency of the time series data, either by upsampling (increasing frequency) or downsampling (decreasing frequency).

In [132]:
newdf =  df.iloc[:10, :]

In [133]:
newdf

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,DaysSinceEpoch,DaysSinceStart
0,1,2010-02-05,1643690.90,0,42.31,2.572,211.096358,8.106,0 days,0 days
1,1,2010-02-12,1641957.44,1,38.51,2.548,211.242170,8.106,7 days,7 days
2,1,2010-02-19,1611968.17,0,39.93,2.514,211.289143,8.106,14 days,14 days
3,1,2010-02-26,1409727.59,0,46.63,2.561,211.319643,8.106,21 days,21 days
4,1,2010-03-05,1554806.68,0,46.50,2.625,211.350143,8.106,28 days,28 days
5,1,2010-03-12,1439541.59,0,57.79,2.667,211.380643,8.106,35 days,35 days
6,1,2010-03-19,1472515.79,0,54.58,2.720,211.215635,8.106,42 days,42 days
7,1,2010-03-26,1404429.92,0,51.45,2.732,211.018042,8.106,49 days,49 days
8,1,2010-04-02,1594968.28,0,62.27,2.719,210.820450,7.808,56 days,56 days
9,1,2010-04-09,1545418.53,0,65.86,2.770,210.622857,7.808,63 days,63 days

In [135]:
## change date column to be index 

newdf.set_index('Date', inplace = True)

In [136]:
newdf

,Store,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,DaysSinceEpoch,DaysSinceStart
Date,,,,,,,,,
2010-02-05,1,1643690.90,0,42.31,2.572,211.096358,8.106,0 days,0 days
2010-02-12,1,1641957.44,1,38.51,2.548,211.242170,8.106,7 days,7 days
2010-02-19,1,1611968.17,0,39.93,2.514,211.289143,8.106,14 days,14 days
2010-02-26,1,1409727.59,0,46.63,2.561,211.319643,8.106,21 days,21 days
2010-03-05,1,1554806.68,0,46.50,2.625,211.350143,8.106,28 days,28 days
2010-03-12,1,1439541.59,0,57.79,2.667,211.380643,8.106,35 days,35 days
2010-03-19,1,1472515.79,0,54.58,2.720,211.215635,8.106,42 days,42 days
2010-03-26,1,1404429.92,0,51.45,2.732,211.018042,8.106,49 days,49 days
2010-04-02,1,1594968.28,0,62.27,2.719,210.820450,7.808,56 days,56 days
2010-04-09,1,1545418.53,0,65.86,2.770,210.622857,7.808,63 days,63 days

In [137]:
newdf.shape

(10, 9)

In [142]:
newdf.select_dtypes(include='number').resample('D').sum()

,Store,Weekly_Sales,Temperature,Fuel_Price,CPI,Unemployment,DaysSinceEpoch,DaysSinceStart
Date,,,,,,,,
2010-02-05,1,1643690.90,42.31,2.572,211.096358,8.106,0 days,0 days
2010-02-06,0,0.00,0.00,0.000,0.000000,0.000,0 days,0 days
2010-02-07,0,0.00,0.00,0.000,0.000000,0.000,0 days,0 days
2010-02-08,0,0.00,0.00,0.000,0.000000,0.000,0 days,0 days
2010-02-09,0,0.00,0.00,0.000,0.000000,0.000,0 days,0 days
...,...,...,...,...,...,...,...,...
2010-04-05,0,0.00,0.00,0.000,0.000000,0.000,0 days,0 days
2010-04-06,0,0.00,0.00,0.000,0.000000,0.000,0 days,0 days
2010-04-07,0,0.00,0.00,0.000,0.000000,0.000,0 days,0 days
2010-04-08,0,0.00,0.00,0.000,0.000000,0.000,0 days,0 days
2010-04-09,1,1545418.53,65.86,2.770,210.622857,7.808,63 days,63 days

## Categorical Data Handling

Pandas provides the categorical class to create a categorical variable. Categorical variables are useful when dealing with data that can be divided into distinct, non-numeric categories.

### Creating Categorical data

In [144]:
categories =  ['Low', 'Medium', 'High']
values =  ['Low', 'High', 'Medium', 'High', 'Low','Medium']

cat_var =  pd.Categorical(values, categories = categories, ordered = True)
print(cat_var)

['Low', 'High', 'Medium', 'High', 'Low', 'Medium']
Categories (3, object): ['Low' < 'Medium' < 'High']

## Create a dummy Variable(One Hot Encoding)
When working with machine learning models or statistical analyses, creating dummy variables is often necessary to represent categorical data numerically. The get_dummies function creates binary columns for each category, effectively converting categorical data into a numerical format.

In [147]:
sample_df =  pd.DataFrame({'Category':['A', 'B', 'C', 'A', 'B', 'C', 'C', 'B', 'C', 'B', 'A', 'B'],
                          })
sample_df

   Category
0         A
1         B
2         C
3         A
4         B
5         C
6         C
7         B
8         C
9         B
10        A
11        B

In [150]:
dummy =  pd.get_dummies(sample_df, dtype = 'int')
dummy

    Category_A  Category_B  Category_C
0            1           0           0
1            0           1           0
2            0           0           1
3            1           0           0
4            0           1           0
5            0           0           1
6            0           0           1
7            0           1           0
8            0           0           1
9            0           1           0
10           1           0           0
11           0           1           0

__Label Encoding__

Another way to handle categorical data is through label encoding, where each category is assigned a unique numerical label. This is useful in scenarios where ordinal relationships exist between categories.

In [151]:
sample_df['LabelEncoded_Category'] =  sample_df['Category'].astype('category').cat.codes
sample_df

   Category  LabelEncoded_Category
0         A                      0
1         B                      1
2         C                      2
3         A                      0
4         B                      1
5         C                      2
6         C                      2
7         B                      1
8         C                      2
9         B                      1
10        A                      0
11        B                      1

# Handling Text data in pandas

In [154]:
titanic =  pd.read_csv('titanic.csv')

In [155]:
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [160]:
'Allen, Mr. William Henry'.split(',')[1].split('.')[0].strip()

'Mr'

In [161]:
titanic['Title'] = titanic['Name'].apply(lambda x: x.split(',')[1].split('.')[0].strip())

In [162]:
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Mr

In [163]:
titanic['Title'].value_counts()

Title
Mr              517
Miss            182
Mrs             125
Master           40
Dr                7
Rev               6
Mlle              2
Major             2
Col               2
the Countess      1
Capt              1
Ms                1
Sir               1
Lady              1
Mme               1
Don               1
Jonkheer          1
Name: count, dtype: int64

In [168]:
## create a cross tab for title and survived columsn

pd.crosstab(index = titanic['Survived'], columns = titanic['Title'])

Title,Capt,Col,Don,Dr,Jonkheer,Lady,Major,Master,Miss,Mlle,Mme,Mr,Mrs,Ms,Rev,Sir,the Countess
Survived,,,,,,,,,,,,,,,,,
0,1,1,1,4,1,0,1,17,55,0,0,436,26,0,6,0,0
1,0,1,0,3,0,1,1,23,127,2,1,81,99,1,0,1,1

In [169]:
titanic['Name_Length'] = titanic['Name'].str.len()

In [170]:
titanic['Name_Length']

0      23
1      51
2      22
3      44
4      24
       ..
886    21
887    28
888    40
889    21
890    19
Name: Name_Length, Length: 891, dtype: int64